# This provides integration into the travis-ci.org CI system. For a overview
# check http://about.travis-ci.org/docs/user/getting-started/
# 
# Some notes:
# - language is "C" because the travis chroot for python installs a non-repo
#   python3.3 from a PPA
sudo: required
dist: trusty
language: c
before_install:
 - sudo apt-get update
 - sudo apt-get install -y pyflakes python3-apt python3-mock python3-distro-info python-apt python-mock python-distro-info
# travis is "funny" it has a non-distro python3 that will not find
# python modules installed via apt-get
script: (cd tests ; PATH=/usr/bin:$PATH make)
